name: Make JSON from TXT

on:
  push:
    branches: [ "main" ]
    
permissions:
    contents: write
    pull-requests: read
    
jobs:

  build_json:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Run json generator
      run: |
        echo repository: $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE/JsonGenerator/net6.0
        dotnet AppxListJsonFromText.dll
        cd ../..
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update json files from txt
        
