name: Make JSON from TXT

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: read

jobs:
  build_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 6.0.x

    - name: Run json generator
      run: |
        echo repository: $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE/JsonGenerator/net6.0
        dotnet AppxListJsonFromText.dll

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update generated files from versions.yaml
