name: Make JSON from TXT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Run json generator
      run: |
        echo repository: $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE/JsonGenerator/net6.0
        dotnet AppxListJsonFromText.dll
        cd ../..
        git remote set-url https://bernarddesfosse:$ACTION_REPOSITORY_ACCESS_TOKEN@github.com/bernarddesfosse/onix_compatible_appx.git
        git config --global user.name bernarddesfosse
        git config --global user.email bernarddesfosse@users.noreply.github.com
        git add .
        git commit -m "Generated JSON Data"
        git push
