name: Make JSON from TXT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Run json generator
      run: |
        echo repository: GITHUB_REPOSITORY
        cd $GITHUB_REPOSITORY
        dotnet JsonGenerator/net6.0/AppxListJsonFromText.dll
        git config user.name JsonBoy
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generated JSON Data"
        git push
